config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :events, :users
  root 'events#index'

  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  post '/drop', to: 'users#drop'
  get '/search', to: 'events#search'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/settings', to: 'users#edit'
  get '/error', to: 'users#error'
  get 'events/new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/charges', to: 'charges#new'
  post '/charges', to: 'charges#create'
  post 'tokens' => "tokens#create"
  post '/expand', to: 'users#expand'
  get '/verify', to:'users#verify'
  post '/verify', to: 'users#verify_check'
  post '/parties', to: 'parties#review'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :parties
  has_many :events, through: :parties
  has_many :charges
  attr_accessor :remember_token, :ssn, :address_street1, :address_street2, :address_city, :address_state, :address_postal_code

  before_save {self.email = email.downcase}
  before_save {self.username = username.downcase}
  validates :username, presence: true, length: { maximum: 50 },
                       uniqueness: {case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #Returns a random User token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  #Forgets a User
  def forget
    update_attribute(:remember_digest, nil)
  end

  #finds name based on id
  def self.name_by_id(search)
    where("id = ?", "#{search}").select(:username)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :drop]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  helper_method :sex_check

  def new
    #prevents user from accessing signup when already logged in
    begin
      @user = User.find(session[:user_id])
      redirect_to @user
    rescue ActiveRecord::RecordNotFound
      @user = User.new
    end
  end

  def index
    #admins only page
    if User.find(session[:user_id]).admin?
      @users = User.paginate(page: params[:page])
    else
      redirect_to root_path
    end
  end

  #profile page
  def show
     @user = User.find(params[:id])
  end

  #edit page
  def edit
    @user = User.find(params[:id])
  end

  #updating profile
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  #drop parties
  def drop
    if params[:id]
      Party.existing(current_user.id,params[:id]).first.destroy
      flash[:success] = "Sucessfully Dropped!"
      redirect_to current_user
    end
  end

  #signup page
  def create
   @user = User.new(user_params)
   if @user.save
     @user.update_attribute(:radius, 5)
     Stripe.api_key = Rails.application.secrets.STRIPE_SECRET_KEY
     customer = Stripe::Customer.create(email: @user.email)
     @user.update_attribute(:customer_id, customer.id)
     @user.update_attribute(:verify, FALSE)
     @user.update_attribute(:card_avail, FALSE)

     #defaults to 5 mile radius
     log_in @user
     flash[:success] = "Welcome to the Fiesto!"
     redirect_to @user


   else
     render 'new'
   end
 end

 #user deletion by admin
 def destroy
   Party.user_deletion(params[:id]).each do |temp|
     temp.destroy
   end
   Event.user_deletion(params[:id]).each do |temp|
     temp.destroy
   end
   User.find(params[:id]).destroy
   flash[:success] = "User deleted"
   redirect_to users_url
 end

 def expand
    if current_user != nil
      current_user.update(:radius => (current_user.radius + 2))
    end
    redirect_to '/'
 end

 def sex_check
   require 'net/http'
   require 'json'
   new_dob = Date.strptime(current_user.dob, "%m/%d/%Y")
   @url = "http://services.familywatchdog.us/rest/json.asp?key=F413B188-9C3B-4A19-A286-6BDEF26A84E1&lite=1&type=searchbynamedob&fname=" + current_user.first_name + "&lname=" + current_user.last_name + "&dob=" + new_dob.strftime("%m") + "/" + new_dob.strftime("%d") + "/" + new_dob.strftime("%Y")

   uri = URI(@url)
   response = Net::HTTP.get(uri)

   h = JSON.parse response
   if h["offenders"][0].nil?
     puts "Not an offender"
     current_user.offender = FALSE
   else
     puts "Is an offender"
     current_user.offender = TRUE
   end
   current_user.save
end

def verify
end

def verify_check
  BlockScore.api_key = 'sk_test_c09ab82974083e676772876a24482e00'

  new_dob = Date.strptime(current_user.dob, "%m/%d/%Y")
  person = BlockScore::Person.create(
    birth_day: new_dob.strftime("%d"),
    birth_month: new_dob.strftime("%m"),
    birth_year: new_dob.strftime("%Y"),
    document_type: 'ssn',
    document_value: '0000',
    name_first: current_user.first_name,
    name_last: current_user.last_name,
    address_street1: "#{params[:address_street1]}",
    address_street2: "#{params[:address_street2]}",
    address_city: "#{params[:address_city]}",
    address_subdivision: "#{params[:address_state]}",
    address_postal_code: "#{params[:address_postal_code]}",
    address_country_code: 'US'
  )

  puts person.status
  if person.status == 'valid'
    current_user.verify = TRUE
    current_user.save
  end
  flash[:success] = "Your identity will be reviewed."
  redirect_to current_user
end

 private
    def user_params
     params.require(:user).permit(:username, :email, :password, :bio,
                                  :password_confirmation, :radius, :first_name, :last_name, :dob, :passcode)
   end

   def logged_in_user
       unless logged_in?
         store_location
         flash[:danger] = "Please log in."
         redirect_to login_url
       end
   end

   # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
end
end

app/views/users/_current.html.erb
<div class="col-md-12 all-events">
    <% Party.all.each do |party| %>
    <% if party.user_id == @user.id %>
        <% @event = Event.find(party.event_id) %>
        <div class="color-box" data-turbolinks="false">
        <p><%= link_to "#{image_tag Event.find(party.event_id).avatar.url(:thumb)}".html_safe, @event %></p>
        <p class="partyname"><strong><%= link_to Event.name_by_id(party.event_id).first.name, @event %></strong></p>
        <p><%= link_to "#{@event.location}", @event %></p>
        <p><%= link_to "#{@event.date}", @event %></p>
        <p><%= link_to "#{number_to_currency(@event.price)}", @event %></p>
        <p><%= link_to 'Delete', { action: "drop", id: party.event_id }, data: { confirm: 'Are you sure?' }, :method => :post %></p>


        <!--if event has passed, option to rate/comment -->
        <% @event = Event.find_by_party(party.event_id) %>
        <% if @event.time < Time.now && Date.strptime(@event.date, "%m/%d/%Y") < DateTime.now && party.attended%>


            <%= form_tag parties_path(:user_id => party.user_id, :event_id => party.event_id) do %>
            <% if party.rating.nil? && party.comment.nil? %>
            <div class="field">
              <%= label_tag 'Rating' %>
              <%= number_field_tag(:rating) %>
            </div>

            <div class="field">
              <%= label_tag 'Comment' %>
              <%= text_field_tag(:comment) %>
            </div>
            <%= submit_tag("Submit") %>
            <% else %>
            <p> Rated: <%= party.rating %> - <%= party.comment %></p>
            <% end %>
          <% end %>
        <% end %>
        </div>
      <% end %>
    <% end %>
</div>

app/views/users/_form.html.erb
 <%= render 'shared/error_messages', object: @user %>

 <body>
   <div class="signup-wrap">
 	<div class="signup-html">
 		<input id="tab-1" type="radio" name="tab" class="sign-in"><label for="tab-1" class="tab"></label>
    <% if logged_in? %>
    <input id="tab-2" type="radio" name="tab" class="sign-up" checked><label for="tab-2" class="tab">Edit Profile</label>
    <% else %>
 		 <input id="tab-2" type="radio" name="tab" class="sign-up" checked><label for="tab-2" class="tab">Sign Up</label>
    <% end %>
    <div class="signup-form">
 			<div class="sign-up-htm">
        <%= form_for(@user) do |f| %>
 				<div class="group">
 					<label for="user" class="label">Username</label>
          <%= f.text_field :username, class: 'input' %>
 				</div>
        <div class="group">
 					<label for="user" class="label">First Name</label>
          <%= f.text_field :first_name, class: 'input' %>
 				</div>
        <div class="group">
 					<label for="user" class="label">Last Name</label>
          <%= f.text_field :last_name, class: 'input' %>
 				</div>
        <div class="group">
 					<label for="user" class="label">Date Of Birth</label>
          <%= f.text_field :dob, class: 'input', :data => {:provide => "datepicker"}%>
 				</div>
        <div class="group">
 					<label for="user" class="label">Email Address</label>
          <%= f.email_field :email, class: 'input' %>
 				</div>
 				<div class="group">
 					<label for="pass" class="label">Password</label>
 					  <%= f.password_field :password, class: 'input' %>
 				</div>
 				<div class="group">
 					<label for="pass" class="label">Password Confirmation</label>
          <%= f.password_field :password_confirmation, class: 'input' %>
 				</div>
        <div class="group">
 					<label for="pass" class="label">Search Radius</label>
          <%= f.number_field :radius, class: 'input' %>
 				</div>
 				<div class="group">
 					<label for="pass" class="label">Passcode</label>
          <%= f.number_field :passcode, class: 'input' %>
 				</div>
        <% if logged_in? %>
        <div class="group">
 					<label for="pass" class="label">Biography</label>
           <%= f.text_area :bio, :rows => "5", class: "input"%>
 				</div>
        <% end %>
 				<div class="group">
          <%= f.submit yield(:button_text), class: "button" %>
 				</div>
        <% if ! logged_in? %>
 				<div class="hr"></div>
 				<div class="foot-lnk">
 					<%= link_to "Already a member? Log in!", login_path, id: "make_white"%>
 				</div>
        <% end %>
        <% end %>
 			</div>
 		</div>
 	</div>
 </div>


 </body>

app/views/users/_host.html.erb
<div class="col-md-12 all-events">
  <% Event.all.each do |event| %>
    <% if event.user_id == current_user.id %>
    <% @event = Event.find(event.id) %>
      <div class="color-box" data-turbolinks="false">
      <p><%= link_to "#{image_tag Event.find(event.id).avatar.url(:thumb)}".html_safe, @event %></p>
      <p class="partyname"><strong><%= link_to Event.name_by_id(event.id).first.name, @event %></strong></p>
      <p><%= link_to "#{@event.location}", @event %></p>
      <p><%= link_to "#{@event.date}", @event %></p>
      <p><%= link_to "#{number_to_currency(@event.price)}", @event %></p>
      </div>
    <% end %>
    <% end %>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.username, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Settings') %>
<% provide(:button_text, 'Save changes') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/error.html.erb
<% provide(:title, 'Error') %>

<h2>Cannot display this page.<h2>

  <div class="row">
  </div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>

<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-8">

      <div class="col-md-4">
        <%= gravatar_for @user %>
      </div>

      <div class="col-md-8 user-info">
        <h1>
          <%= @user.username %>
          <% if @user.offender %>
          <%= image_tag 'offender-icon.png', id: 'offender-icon' %>
          <% end %>
          <% if @user.offender == FALSE %>
          <%= image_tag('safe-icon.png', id: 'safe-icon') %>
          <% end %>
        </h1>
        <div class="user-bio">
          <% if @user.bio.nil? %>
          Add a bio under <%= link_to 'Settings', edit_user_path(current_user) %>
          <% else %>
          <p><%= @user.bio %></p>

          <!-- <p>"I love tacos!"</p>
          <p> 21-year old college student from New York and attending college in Boston. Gonna be graduating this year so hit me up with parties!</p> -->
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-xs-6 col-md-4">
      <div class="party-stat-group">
        <h4>Parties RSVP</h4>
        <p class="party-stat"><%= Party.where(:user_id => @user.id).count %></p>
        <h4>Parties Hosted</h4>
        <p class="party-stat"><%= Event.where(:user_id => @user.id).count %></p>
      </div>
    </div>
  </div>
</div>

<!--- sex offend check yet? -->
<% if @user.verify && @user.offender.nil? %>
  <p> enter verify check </p>
  <% sex_check %>
<% end %>

<div class="col-md-12 all-events">
    <div class="tab">
        <button class="tablinks" onclick="load(event, 'host_div')", id="defaultOpen">My Parties</button>
        <button class="tablinks" onclick="load(event, 'current_div')">Parties I Am Attending</button>
    </div>

      <div id="host_div" class="tabcontent"><%= render 'host' %></div>
      <div id="current_div" class="tabcontent"><%= render 'current' %></div>
</div>

<%= javascript_include_tag "event_render" %>

app/views/users/verify.html.erb
<body>
  <div class="signup-wrap" id="bgwrap">
 <div class="signup-html">
   <input id="tab-1" type="radio" name="tab" class="sign-in"><label for="tab-1" class="tab"></label>
   <input id="tab-2" type="radio" name="tab" class="sign-up" checked><label for="tab-2" class="tab">Background Check</label>
   <div class="signup-form">
     <div class="sign-up-htm">
       <p>Enter 0000 for a valid status/0001 for an invalid status in SSN field</p>
       <%= form_tag verify_path do %>
       <div class="group">
         <label for="user" class="label">Last Four Digits of SSN</label>
           <%= number_field_tag :ssn, nil, class: 'input' %>
       </div>

       <div class="group">
       <label for="user" class="label">Address Line 1</label>
          <%= text_field_tag :address_street1, nil,class: 'input' %>
        </div>

        <div class="group">
          <label for="user" class="label">Address Line 2</label>
            <%= text_field_tag :address_street2, nil, :class=> 'input' %>
        </div>

        <div class="group">
          <label for="user" class="label">City</label>
            <%= text_field_tag :address_city, nil, :class=> 'input' %>
        </div>

       <div class="group">
         <label for="user" class="label">State of Residence</label>
           <%= select_tag :address_state, options_for_select(us_states), class: 'input'%>
       </div>
       <div class="group">
         <label for="pass" class="label">Postal Code</label>
         <%= text_field_tag :address_postal_code, nil, class: 'input' %>
       </div>
       <div class="group">
         <%= submit_tag("Verify",:class=>"button", :name=>"submit") %>
       </div>
       <% end %>
     </div>
   </div>
 </div>
</div>


</body>