config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :events, :users
  root 'events#index'

  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  post '/drop', to: 'users#drop'
  get '/search', to: 'events#search'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/settings', to: 'users#edit'
  get '/error', to: 'users#error'
  get 'events/new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/charges', to: 'charges#new'
  post '/charges', to: 'charges#create'
  post 'tokens' => "tokens#create"
  post '/expand', to: 'users#expand'
  get '/verify', to:'users#verify'
  post '/verify', to: 'users#verify_check'
  post '/parties', to: 'parties#review'

end

app/models/event.rb
class Event < ApplicationRecord
  has_many :parties
  has_many :users, through: :parties
  belongs_to :user
  geocoded_by :location   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  attr_accessor :routing, :account

  validates :name, presence: true, length: { maximum: 50 }
  validates :location, presence: true
  validates :time, presence: true

  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :avatar, :styles => {
    :thumb    => ['200x200#',  :jpg, :quality => 70],
    :preview  => ['480x480#',  :jpg, :quality => 70],
    :large    => ['600>',      :jpg, :quality => 70],
    :retina   => ['1200>',     :jpg, :quality => 30]
  },
  :convert_options => {
    :thumb    => '-set colorspace sRGB -strip',
    :preview  => '-set colorspace sRGB -strip',
    :large    => '-set colorspace sRGB -strip',
    :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
  },
  :url => "http://fiesto-app.s3.amazonaws.com/images/:attachment/:id/:basename_:style.:extension",
  :default_url => "/images/normal/missing.png"

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  def self.name_by_id(search)
    where("id = ?", "#{search}").select(:name)
  end

  def self.user_deletion(u_id)
    where("user_id = ?" , "#{u_id}")
  end

  def self.find_by_party(event_id)
    where("id = ?", "#{event_id}").first
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  include EventsHelper
  helper_method

  # GET /events
  # GET /events.json
  def index
    latitude = cookies["latitude"]
    longitude = cookies["longitude"]
    #set default lat long to brandeis if cookies doesn't have it
    if latitude == nil || longitude == nil
      latitude = 42.3647
      longitude = -71.2588
    end
    @heat = FALSE
    if current_user != nil
      if current_user.radius == nil
        current_user.radius = 6
      end
      #search based on search radius
      @my_events = Event.user_deletion(current_user.id)
      @events = Event.near([latitude,longitude], current_user.radius)
      current_user.update(:latitude => latitude)
      current_user.update(:longitude => longitude)
        new_radius = current_user.radius + 2
      @heat_zone = Event.near([latitude,longitude], new_radius)
      if @heat_zone != nil
        if @heat_zone.count(:all) - @events.count(:all) > 5
          @heat = TRUE
        end
      end
    else
      #search based on
      @my_events = nil
      @events = Event.all
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @party = Party.all
    gon.latlong = calc_cor (@event.location)
    @map = map
  end

  #Party Signups
  def join
    if params[:id]
      @party = Party.existing(current_user.id, params[:id]).first
        if @party == nil
          @party = Party.new(user_id: current_user.id, event_id: params[:id])
          @party.save
          flash[:success] = "Sucessfully Joined!"
          redirect_to current_user
        else
          flash[:danger] = "You already signed up for this."
          redirect_to current_user
        end
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @current = User.find_by id: session[:user_id]
    @event.user_id = @current.id

    puts @event.routing
    puts "enter create"
    if @event.routing.present? && @event.account.present?
      @date = Date.strptime(current_user.dob, "%m/%d/%Y")
      puts "enter first if"
      Stripe.api_key = Rails.application.secrets.STRIPE_SECRET_KEY

      acct = Stripe::Account.create(
      {
        :country => 'US',
        :managed => true,
        :external_account => {
          :object => 'bank_account',
          :country => 'US',
          :currency => 'usd',
          :routing_number => @event.routing,
          :account_number => @event.account,
        }
      }
      )

      acct.legal_entity.dob.day = @date.strftime("%d")
      acct.legal_entity.dob.month = @date.strftime("%m")
      acct.legal_entity.dob.year = @date.strftime("%Y")
      acct.legal_entity.first_name = current_user.first_name
      acct.legal_entity.last_name = current_user.last_name
      acct.legal_entity.type = "individual"
      acct.tos_acceptance.date = Time.now.to_i
      acct.tos_acceptance.ip = request.remote_ip
      acct.save
      current_user.update_attributes(:account_id => acct.id)
    end

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    #destroys relationships
    Party.deletion(@event.id).each do |temp|
      temp.destroy
    end
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :time, :location, :avatar, :price, :routing, :account)
    end
end

app/helpers/events_helper.rb
require 'open-uri'
require 'ostruct'
require 'json'

module EventsHelper

  def calc_cor (location)
    key = "AIzaSyB8Y2tnZHjBCcyXWJNpqeVqXgeJLLcfk5c"
    url = "https://maps.googleapis.com/maps/api/geocode/json?address=#{location}&key=#{key}"
    json_response = open(url).read
    response = JSON.parse(json_response)
    begin
      coordinates = response['results'][0]['geometry']['location']
      return coordinates
    rescue NoMethodError
      return JSON.parse('{"lat" : 42.36637398029149,"lng" : -71.2535282197085}')
    end
  end

  def map
    key = "AIzaSyB8Y2tnZHjBCcyXWJNpqeVqXgeJLLcfk5c"
    url = "https://maps.googleapis.com/maps/api/js?key=#{key}&callback=initMap"
    response = open(url).read
    return response
  end

  def guest?
    Party.all.each do |party|
      if party.user_id == current_user.id
        return true
      end
    end
    return false
  end


end

app/views/events/_all.html.erb
<div class="col-md-12 all-events">
    <% Event.all.each do |event| %>
        <div class="color-box" data-turbolinks="false">
          <p><%= link_to "#{image_tag event.avatar.url(:thumb)}".html_safe, event %></p>
          <p class="partyname"><strong><%= link_to "#{event.name}", event %></strong></p>
          <p><%= link_to "#{event.location}", event %></p>
          <p><%= link_to "#{event.date}", event %></p>
          <p><%= link_to "#{number_to_currency(event.price)}", event %></p>
        </div>
    <% end %>
</div>

app/views/events/_bank_account.html.erb
<div class="field">
  <label for="field1">
  <span>Routing No.</span>
  <%= f.text_field :routing %>
  </label>
</div>

<div class="field">
  <label for="field1">
  <span>Account No.</span>
  <%= f.text_field :account %>
  </label>
</div>

app/views/events/_form.html.erb
<% if event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

    <ul>
    <% event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for (event), :html => { :class => "form-style-4" } do |f| %>

  <div id="form_header">
    <h1 id="formtitle">Add A New Party!</h1>
  </div>

  <div class="field">
    <label for="field1">
    <span>Party Name</span>
    <%= f.text_field :name%>
  </label>
  </div>

  <div class="field">
    <label for="field1">
    <span>Date</span>
    <%= f.text_field :date, :data => {:provide => "datepicker"}%>
    </label>
  </div>

  <div class="field">
    <label for="field1">
    <span>Time</span>
      <%= f.text_field :time, class: "timepicker"%>
    </label>
  </div>

  <div class="field">
    <label for="field1">
    <span>Location</span>
    <%= f.text_field :location%>
    </label>
  </div>

  <div class="field">
    <label for="field1">
    <span>Price</span>
    <%= f.number_field :price, :step => 0.01 %>
    </label>
  </div>

  <div class="field">
    <label for="field1">
    <span>Image</span>
    <%= f.file_field :avatar, label: "Event Picture"%>
    </label>
  </div>

  <% if current_user.account_id.nil? %>
    <%= render 'bank_account', f: f %>
  <% end %>


  <div class="actions" type="button">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_form2.html.erb
<% if event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

    <ul>
    <% event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for (event), :html => { :class => "form-style-4" } do |f| %>

  <div id="form_header">
    <h1 id="formtitle">Edit Your Party!</h1>
  </div>

  <div class="field">
    <label for="field1">
    <span>Party Name</span>
    <%= f.text_field :name%>
  </label>
  </div>

  <div class="field">
    <label for="field1">
    <span>Date</span>
    <%= f.text_field :date, :data => {:provide => "datepicker"}%>
    </label>
  </div>

  <div class="field">
    <label for="field1">
    <span>Time</span>
      <%= f.text_field :time, class: "timepicker"%>
    </label>
  </div>

  <div class="field">
    <label for="field1">
    <span>Location</span>
    <%= f.text_field :location%>
    </label>
  </div>

  <div class="field">
    <label for="field1">
    <span>Price</span>
    <%= f.number_field :price, :step => 0.01 %>
    </label>
  </div>

  <div class="field">
    <label for="field1">
    <span>Image</span>
    <%= f.file_field :avatar, label: "Event Picture"%>
    </label>
  </div>

  <% if current_user.account_id.nil? %>
    <%= render 'bank_account', f: f %>
  <% end %>


  <div class="actions" type="button">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_host.html.erb
<% if logged_in? %>
<div class="col-md-12 all-events">
    <% @my_events.each do |event| %>
        <div class="color-box" data-turbolinks="false">
          <p><%= link_to "#{image_tag event.avatar.url(:thumb)}".html_safe, event %></p>
          <p class="partyname"><strong><%= link_to "#{event.name}", event %></strong></p>
          <p><%= link_to "#{event.location}", event %></p>
          <p><%= link_to "#{event.date}", event %></p>
          <p><%= link_to "#{number_to_currency(event.price)}", event %></p>
        </div>
    <% end %>
</div>
<% end %>

app/views/events/_near.html.erb
<div class="col-md-12 all-events">
    <% @events.each do |event| %>
        <div class="color-box" data-turbolinks="false">
          <p><%= link_to "#{image_tag event.avatar.url(:thumb)}".html_safe, event %></p>
          <p class="partyname"><strong><%= link_to "#{event.name}", event %></strong></p>
          <p><%= link_to "#{event.location}", event %></p>
          <p><%= link_to "#{event.date}", event %></p>
          <p><%= link_to "#{number_to_currency(event.price)}", event %></p>
        </div>
    <% end %>
</div>

app/views/events/_results.html.erb
<h1>Search Results</h1>
<div class="col-md-12 all-events">
    <% @searchevent.each do |event| %>
      <div class="own-event">
        <div class="color-box">
        <p><%= image_tag event.avatar.url(:thumb) %></p>
        <p><%= link_to "#{event.name}", event %></p>
        </div>
      </div>
    <% end %>
</div>

app/views/events/edit.html.erb
<%= render 'form2', event: @event %>

<%= button_to 'Show', @event , id: "back_button", method: "get"%>
<%= button_to 'Back', events_path, id: "back_button", method: "get"%>

app/views/events/index.html.erb
<div class="top-section">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <% count = 0 %>
            <% Event.all.each do |event| %>
            <% if count == 0 %>
            <li data-target="#myCarousel" data-slide-to="<%= count %>" class="active"></li>
        <% else %>
            <li data-target="#myCarousel" data-slide-to="<%= count %>"></li>
            <% end %>
            <% count = count + 1 %>
            <% end %>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <% count2 = 0 %>
            <% Event.all.each do |event| %>
            <% if count2 == 0 %>
            <div class="item active">
                <%= link_to "#{image_tag event.avatar.url(:preview)}".html_safe, event %>
            </div>
            <% else %>
            <div class="item">
                <%= link_to "#{image_tag event.avatar.url(:preview)}".html_safe, event %>
            </div>
            <% end %>
            <% count2 = count2 + 1 %>
            <% end %>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="carousel-text">
        <div class="text-pos">
            <p>Check out the parties that are trending right now.</p>
            <p class="font-orange">RSVP now.</p>
            <br>
            <p>Make your nights come alive!
            </div>
        </div>
    </div>

    <div class="col-md-12 all-events">
        <div class="tab">
            <button class="tablinks" onclick="load(event, 'near_div')" , id="defaultOpen">Nearby Parties</button>
            <button class="tablinks" onclick="load(event, 'host_div')">My Parties</button>
            <button class="tablinks" onclick="load(event, 'all_div')">All Parties</button>
        </div>

        <div id="near_div" class="tabcontent"><%= render 'near' %></div>
        <div id="host_div" class="tabcontent"><%= render 'host' %></div>
        <div id="all_div" class="tabcontent"><%= render 'all' %></div>

    </div>

    <div id="floater">
        <% if logged_in? %>
        <%= link_to 'New Party', new_event_path, class: "new_event_button"%>
    <% else %>
        <%= link_to 'Log In', login_path, method: "get", class: "new_event_button" %>
        <% end %>
    </div>

    <div id="floater2">
        <% if @heat && logged_in?%>
        <%= button_to 'Expand Radius', '/expand', :method => :post, :class => 'heat_button'%>
        <% end %>
    </div>

    <%= javascript_include_tag "event_render" %>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

<%= button_to 'Back', events_path, id: "back_button", method: "get"%>

app/views/events/show.html.erb
<%= include_gon %>

<div class="brand">
    <div id='chat_name'><%= @event.name %></div>
</div>
<div class="address-bar">
    <div id="address">
        <%= @event.location %>
    </div>
</div>

<div class="container">

    <div class="row">
        <div class="box">
            <div class="col-lg-12 text-center">
            <h2>
                <%= link_to '&larr;'.html_safe, "/", class: "event_text"%>
                <% if logged_in? && !Party.party_exist(current_user.id, @event.id) && current_user.id != @event.user_id %>
                  <% if current_user.card_avail %>
                  <%= link_to 'RSVP', charges_path(:id => @event.id), method: :post, class: "event_text" %>
                  <% else %>
                  <%= link_to 'RSVP', charges_path(:event_id => @event.id, :event_price => @event.price.to_f, :event_host => @event.user_id, :id => @event.id), class: "event_text" %>
                  <% end %>
                <% end %>
                <% if logged_in? && @event.user_id == current_user.id%>
                  <%= link_to 'Edit', edit_event_path(@event), class: "event_text"%>
                  <%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "event_text"%>
                <% end %>
</h2>
                <h2 class="brand-before">
                    <small>Join</small>
                </h2>
                <h1 class="brand-name"><%= image_tag @event.avatar.url(:large), id: "event_image"%></h1>
                <h2>
                    <small>Hosted By
                        <% @host = User.find_by id: @event.user_id %>
                        <strong><%= @host.username %></strong>
                    </small>
                </h2>
                <h2>
                    <small>
                        On
                        <%= Date.strptime(@event.date, "%m/%d/%Y") %>
                        at
                        <%= @event.time.to_time.strftime("%I:%M%p") %>
                    </small>
                </h2>
                <strong>Price:</strong>
                    <%= number_to_currency(@event.price) %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h2 class="intro-text text-center">
                    <strong>Map</strong>
                </h2>
                <hr>
                <hr class="visible-xs">
                <div id="map"></div>
            </p>
        </div>
    </div>
</div>
<% if logged_in? %>
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">
                <strong>Guest List</strong>
            </h2>
            <hr>
            <table>
                <thead>
                    <tr>
                        <th>Guest Name</th>
                        <% if logged_in? && current_user.id == @event.user_id %>
                        <th>Password</th>
                        <% end %>
                        <th colspan="10"></th>
                    </tr>
                </thead>

                <tbody>
                    <% @party.each do |party| %>
                    <% if party.event_id == @event.id %>
                    <tr>
                        <!--- traverse through each party and list guests and attend button to charge -->
                        <td>
                            <% if logged_in? && @event.user_id == current_user.id%>
                            <%= link_to User.name_by_id(party.user_id).first.username, User.find(party.user_id) %>
                        <% else %>
                            <%= User.name_by_id(party.user_id).first.username %>
                            <% end %>
                        </td>

                        <% if logged_in? && @event.user_id == current_user.id %>
                        <td>
                            <% if Party.find_by_id(party.id).attended %>
                            Paid. Attending right now.
                        <% else %>
                            <%= form_tag charges_path(:user_id => party.user_id, :event_price => @event.price.to_f, :event_host => @event.user_id, :id => @event.id, :party_id => party.id) do %>
                            <div class="field">
                                <%= text_field_tag(:enter) %>
                            </div>

                        </td>
                        <td>
                            <%= submit_tag("Attend") %>
                            <% end %>
                            <% end %>
                        </td>
                        <% end %>
                        <% end %>
                        <% end %>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<% if (current_user.id == @event.user_id) || guest?%>
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">
                <strong>Party Chatroom</strong>
                <p />
                <% if current_user.id == @event.user_id %>
                  <small>May need to refresh after event creation</small>
                <% end %>
            </h2>
            <hr>
            <div id="messages" class = "nothing"></div>
            <input id="chat-input" class="form-control" type="text" placeholder="say anything"/>
        </div>
    </div>
</div>
<% end %>

<div class="row">
<div class="box">
    <div class="col-lg-12">
        <hr>
        <h2 class="intro-text text-center">
            <strong>Reviews</strong>
        </h2>
        <hr>
        <% $average = 0 %>
        <% $num = 0 %>

        <!-- Rating and comments for party -->
        <!---if event has already passed? -->
        <% if @event.time < Time.now && Date.strptime(@event.date, "%m/%d/%Y") < DateTime.now %>
        <% Party.all.each do |party| %>
        <% if party.event_id == @event.id && !party.rating.nil?%>
        <% $average = $average + party.rating %>
        <% $num = $num + 1 %>
        <p>Rating by
            <%= User.name_by_id(party.user_id).first.username %>:
            <%= party.rating %>, Comment:
            <%= party.comment %></p>
        <% end %>
        <% end %>
        <% if $average != 0 && $num != 0 %>
        <% $average = $average/$num %>
        <p>
            Average rating:
            <%= $average.to_f %></p>
        <% end %>
        <% end %>
    </div>
</div>
</div>
<% end %>

</div>

<%= javascript_include_tag "map" %>
<%= javascript_include_tag '//media.twiliocdn.com/sdk/rtc/js/ip-messaging/v0.8/twilio-ip-messaging.min.js' %>
<%= javascript_include_tag "chat" %>
<script async defer>
<%= raw @map %>
</script>