config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :events, :users
  root 'events#index'

  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  post '/drop', to: 'users#drop'
  get '/search', to: 'events#search'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/settings', to: 'users#edit'
  get '/error', to: 'users#error'
  get 'events/new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/charges', to: 'charges#new'
  post '/charges', to: 'charges#create'
  post 'tokens' => "tokens#create"
  post '/expand', to: 'users#expand'
  get '/verify', to:'users#verify'
  post '/verify', to: 'users#verify_check'
  post '/parties', to: 'parties#review'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.railstutorial.org/">Fiesto, the College Party App</a>
    by <a href="https://www.facebook.com/its.only.lifee">Kelvin Mei</a>
       <a href="https://www.facebook.com/erie.chai">Erica Chai</a>
       <a href="https://www.facebook.com/jorden.rabasco">Jorden Rabasco</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contacts_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <%= link_to image_tag("fiesto.ico", size: "20x20", id: "hat-icon"), root_path %>
      <%= link_to "Fiesto", root_path, id: "logo"%>
      <ul class="nav navbar-nav navbar-right">
        <li class="navbutton"><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
          <li class="navbutton"><%= link_to "Users", users_path %></li>
          <% end %>
          <li class="dropdown" id = "nav-dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <% if !current_user.verify %>
                <li><%= link_to "Verify Identity", verify_path %></li>
              <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="navbutton"><%= link_to "Log in", login_path %></li>
          <li class="navbutton"><%= link_to "Sign Up", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fiesto The Party App</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'fiesto.ico'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div id="out"></div>
    <div class="container" id="main">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

<script>
// $(document).on('turbolinks:load', function(){
//   var x = document.cookie;
//   x =
//   console.log('wtf');
//   console.log(x);
//
//
// });

</script>